"""initial content and time-series tables

Revision ID: 77fb940a2353
Revises: 
Create Date: 2026-08-02 21:29:54.807315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '77fb940a2353'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_external_id'), 'content', ['external_id'], unique=True)
    op.create_index(op.f('ix_content_publish_date'), 'content', ['publish_date'], unique=False)
    op.create_index(op.f('ix_content_type'), 'content', ['type'], unique=False)
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('new_viewer_percentage', sa.Float(), nullable=True),
    sa.Column('returning_viewer_percentage', sa.Float(), nullable=True),
    sa.Column('top_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audience_content_captured', 'audience', ['content_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_audience_captured_at'), 'audience', ['captured_at'], unique=False)
    op.create_index(op.f('ix_audience_content_id'), 'audience', ['content_id'], unique=False)
    op.create_table('engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engagement_content_captured', 'engagement', ['content_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_engagement_captured_at'), 'engagement', ['captured_at'], unique=False)
    op.create_index(op.f('ix_engagement_content_id'), 'engagement', ['content_id'], unique=False)
    op.create_table('metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('watch_time_hours', sa.Float(), nullable=True),
    sa.Column('average_view_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_snapshot_content_captured', 'metrics_snapshot', ['content_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_metrics_snapshot_captured_at'), 'metrics_snapshot', ['captured_at'], unique=False)
    op.create_index(op.f('ix_metrics_snapshot_content_id'), 'metrics_snapshot', ['content_id'], unique=False)
    op.create_table('retention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retention_content_captured', 'retention', ['content_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_retention_captured_at'), 'retention', ['captured_at'], unique=False)
    op.create_index(op.f('ix_retention_content_id'), 'retention', ['content_id'], unique=False)
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_content_captured', 'traffic', ['content_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_traffic_captured_at'), 'traffic', ['captured_at'], unique=False)
    op.create_index(op.f('ix_traffic_content_id'), 'traffic', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_content_id'), table_name='traffic')
    op.drop_index(op.f('ix_traffic_captured_at'), table_name='traffic')
    op.drop_index('ix_traffic_content_captured', table_name='traffic')
    op.drop_table('traffic')
    op.drop_index(op.f('ix_retention_content_id'), table_name='retention')
    op.drop_index(op.f('ix_retention_captured_at'), table_name='retention')
    op.drop_index('ix_retention_content_captured', table_name='retention')
    op.drop_table('retention')
    op.drop_index(op.f('ix_metrics_snapshot_content_id'), table_name='metrics_snapshot')
    op.drop_index(op.f('ix_metrics_snapshot_captured_at'), table_name='metrics_snapshot')
    op.drop_index('ix_metrics_snapshot_content_captured', table_name='metrics_snapshot')
    op.drop_table('metrics_snapshot')
    op.drop_index(op.f('ix_engagement_content_id'), table_name='engagement')
    op.drop_index(op.f('ix_engagement_captured_at'), table_name='engagement')
    op.drop_index('ix_engagement_content_captured', table_name='engagement')
    op.drop_table('engagement')
    op.drop_index(op.f('ix_audience_content_id'), table_name='audience')
    op.drop_index(op.f('ix_audience_captured_at'), table_name='audience')
    op.drop_index('ix_audience_content_captured', table_name='audience')
    op.drop_table('audience')
    op.drop_index(op.f('ix_content_type'), table_name='content')
    op.drop_index(op.f('ix_content_publish_date'), table_name='content')
    op.drop_index(op.f('ix_content_external_id'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
